[package]
name = "wjj-std-examples"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Examples for wjj-std"
publish = false

[dev-dependencies]
wjj-std = { path = "../wjj-std", features = ["full"] }
tokio = { workspace = true, features = ["full"] }
serde_json.workspace = true
linkme.workspace = true
